theme = "lynx"
title = "Halcyon Straits - Links"

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[author]
  name = "@halcyonstraits"
  headline = "BJD Collector - Sewing, Photography, and Videos"
  image = "portait-of-love.jpg"
  links = [
    { halcyonstraits = { href = "https://www.halcyonstraits.com", text = "Doll Profiles" } },
    { youtube = "https://youtube.com/HalcyonStraits" },
    { instagram = "https://instagram.com/halcyonstraits"},
    { discord = "http://discordapp.com/users/809496694122348586"},
    { doa = { href = "https://denofangels.com/threads/feedback-for-veralyne.831734/", text = "Den of Angels" } },
    
  ]

[markup.highlight]
  noClasses = false

[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true
