theme = "lynx"
title = "Halcyon Straits - Links"

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[author]
  name = "Halcyon Straits"
  headline = "BJD Collector - Sewing, Photography, and Videos"
  image = "hs-2022-logo.png"
  links = [
    { halcyonstraits = { href = "https://www.halcyonstraits.com", text = "My Website" } },
    { youtube = "https://youtube.com/HalcyonStraits" },
    { instagram = "https://instagram.com/halcyonstraits"},
    { discord = "https://discord.gg/9C4StDV98x"},
    { doa = { href = "https://denofangels.com/threads/feedback-for-veralyne.831734/", text = "Den of Angels" } },
    
  ]

[markup.highlight]
  noClasses = false

[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true
